# Public Key	GC3SVTWGHVECUE3OTTJY3S2UZ5WWBB42BVT3F2ZZ2EON3EQ6ST6FSQS6
# Secret Key	SBNEDR3C2S6QQGMABRJCNILAY2O25ZYASW7YQTQQQWJNIXPADSIWPHNK

# GCAWQPXXFSYXQD35ZDYZGYL7C4HMEPMUZ7YBQQQ2RHXB22UNPITUZWB2
# SDRISF6ZHIPR4HR7QTMC6IGEK5DHZHJ6DMXUZDKG2DLJRXCGS64CXKZS
#
# GCFXXE6SQWGMJMQAKWC4Q5TQL734FCOFYGYHEJ4PZF7IMJTJSEMVMIFM
# SCQKIDJRXU6Y5DVMVKIQVVODHKL6VRV3R3DKZWBLVN5OSDDX7LPHN6NX

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
ACCOUNTS = ["GCAWQPXXFSYXQD35ZDYZGYL7C4HMEPMUZ7YBQQQ2RHXB22UNPITUZWB2", "GC3SVTWGHVECUE3OTTJY3S2UZ5WWBB42BVT3F2ZZ2EON3EQ6ST6FSQS6"]
VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "mg-test"
ORG_URL = "mg-test.astrify.com"
