NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
ACCOUNTS = ["GDPOJXSGPE37WXQ7GMKMY7EHGA33UMIIXBRYC772YMH2CZOVN36U3SFB", "GBGP7LM3QSKZTDR6JFHHW57UJCNYCEBA3K4GPXARREVNJ4JF722G6RWY"]
VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "mg-test"
ORG_URL = "https://manuelagar.github.io/test/"
